version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mahir-trade-be:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    depends_on:
      - postgres
    environment:
      PG_HOST: postgres
      PG_PORT: "5432"
      PG_DBUSER: postgres
      PG_DBPASS: postgres
      PG_DBNAME: mahir-trade

volumes:
  postgres_data:
    driver: local