CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE "users" (
  "user_id" BIGSERIAL not NULL,
  "uuid" uuid DEFAULT uuid_generate_v4(),
  "phone_number" varchar(40) NOT NULL,
  "password" varchar(255) NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "fullname" varchar(255) NOT NULL,
  "username" varchar(255) UNIQUE NOT NULL,
  "discord_username" varchar(255),
  "google_account_id" varchar(255),
  "created_at" timestamp DEFAULT now(),
  "created_by" varchar(100) default 'SYSTEM',
  "updated_at" timestamp DEFAULT now(),
  "updated_by" varchar(100) default 'SYSTEM',
  "deleted_at" timestamp,
  "deleted_by" varchar(100),
  CONSTRAINT users_pkey PRIMARY KEY (user_id)
);

CREATE TABLE "groups" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid DEFAULT uuid_generate_v4(),
  "group_name" text NOT NULL,
  "created_at" timestamp DEFAULT now(),
  "created_by" varchar(100) default 'SYSTEM',
  "updated_at" timestamp DEFAULT now(),
  "updated_by" varchar(100) default 'SYSTEM',
  "deleted_at" timestamp,
  "deleted_by" varchar(100)
);

CREATE TABLE "modules" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid DEFAULT uuid_generate_v4(),
  "group_id" BIGINT,
  "module_name" text NOT NULL,
  "thumbnail_url" text,
  "tag" varchar(255),
  "created_at" timestamp DEFAULT now(),
  "created_by" varchar(100) default 'SYSTEM',
  "updated_at" timestamp DEFAULT now(),
  "updated_by" varchar(100) default 'SYSTEM',
  "deleted_at" timestamp,
  "deleted_by" varchar(100)
);

CREATE TABLE "sub_modules" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid DEFAULT uuid_generate_v4(),
  "module_id" BIGINT NOT NULL,
  "sub_module_name" text NOT NULL,
  "title" varchar(255),
  "video_url" text NOT NULL,
  "created_at" timestamp DEFAULT now(),
  "created_by" varchar(100) default 'SYSTEM',
  "updated_at" timestamp DEFAULT now(),
  "updated_by" varchar(100) default 'SYSTEM',
  "deleted_at" timestamp,
  "deleted_by" varchar(100)
);

CREATE TABLE "reports" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid DEFAULT uuid_generate_v4(),
  "report_thumbnail_url" text,
  "report_file_url" text,
  "created_at" timestamp DEFAULT now(),
  "created_by" varchar(100) default 'SYSTEM',
  "updated_at" timestamp DEFAULT now(),
  "updated_by" varchar(100) default 'SYSTEM',
  "deleted_at" timestamp,
  "deleted_by" varchar(100)
);

CREATE TABLE "user_sub_modules" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "uuid" uuid DEFAULT uuid_generate_v4(),
  "user_id" BIGINT,
  "sub_module_id" BIGINT,
  "created_at" timestamp DEFAULT now(),
  "created_by" varchar(100) default 'SYSTEM',
  "updated_at" timestamp DEFAULT now(),
  "updated_by" varchar(100) default 'SYSTEM',
  "deleted_at" timestamp,
  "deleted_by" varchar(100),
  PRIMARY KEY ("id", "user_id", "sub_module_id")
);

CREATE TABLE "packages" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid DEFAULT uuid_generate_v4(),
  "price" float,
  "duration_in_month" int,
  "description" text,
  "created_at" timestamp DEFAULT now(),
  "created_by" varchar(100) default 'SYSTEM',
  "updated_at" timestamp DEFAULT now(),
  "updated_by" varchar(100) default 'SYSTEM',
  "deleted_at" timestamp,
  "deleted_by" varchar(100)
);

CREATE TABLE "user_memberships" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "uuid" uuid DEFAULT uuid_generate_v4(),
  "user_id" BIGINT,
  "package_id" BIGINT,
  "expired_at" timestamp,
  "is_membership_active" bool,
  "created_at" timestamp DEFAULT now(),
  "created_by" varchar(100) default 'SYSTEM',
  "updated_at" timestamp DEFAULT now(),
  "updated_by" varchar(100) default 'SYSTEM',
  "deleted_at" timestamp,
  "deleted_by" varchar(100)
);

CREATE TABLE "orders" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid DEFAULT uuid_generate_v4(),
  "user_id" BIGINT,
  "package_id" BIGINT,
  "status" varchar(30),
  "payment_code" varchar(255),
  "created_at" timestamp DEFAULT now(),
  "created_by" varchar(100) default 'SYSTEM',
  "updated_at" timestamp DEFAULT now(),
  "updated_by" varchar(100) default 'SYSTEM',
  "deleted_at" timestamp,
  "deleted_by" varchar(100)
);

CREATE TABLE "transactions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid DEFAULT uuid_generate_v4(),
  "order_id" BIGINT,
  "amount" float,
  "settlement_date" timestamp,
  "webhook_id" uuid,
  "created_at" timestamp DEFAULT now(),
  "created_by" varchar(100) default 'SYSTEM',
  "updated_at" timestamp DEFAULT now(),
  "updated_by" varchar(100) default 'SYSTEM',
  "deleted_at" timestamp,
  "deleted_by" varchar(100)
);

CREATE TABLE "general_logs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" uuid DEFAULT uuid_generate_v4(),
  "user_id" BIGINT,
  "raw_body" jsonb,
  "created_at" timestamp DEFAULT now(),
  "created_by" varchar(100) default 'SYSTEM',
  "updated_at" timestamp DEFAULT now(),
  "updated_by" varchar(100) default 'SYSTEM',
  "deleted_at" timestamp),
  "deleted_by" varchar(100)
);

ALTER TABLE "user_sub_modules" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "user_sub_modules" ADD FOREIGN KEY ("sub_module_id") REFERENCES "sub_modules" ("id");

ALTER TABLE "sub_modules" ADD FOREIGN KEY ("module_id") REFERENCES "modules" ("id");

ALTER TABLE "modules" ADD FOREIGN KEY ("group_id") REFERENCES "groups" ("id");

ALTER TABLE "user_memberships" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "user_memberships" ADD FOREIGN KEY ("package_id") REFERENCES "packages" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "orders" ADD FOREIGN KEY ("package_id") REFERENCES "packages" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");


-- INDEX FOR SEARCHING AND SORTING
CREATE INDEX "idx_module_id" ON "modules" ("group_id" DESC);
CREATE INDEX "idx_sub_module_id" ON "sub_modules" ("module_id" DESC);
CREATE INDEX "idx_user_sub_user_id" ON "user_sub_modules" ("user_id" DESC);
CREATE INDEX "idx_user_sub_module_id" ON "user_sub_modules" ("sub_module_id" DESC);
CREATE INDEX "idx_membership_user_id" ON "user_memberships" ("user_id"DESC);
CREATE INDEX "idx_membership_user_package_id" ON "user_memberships" ("package_id" DESC);
CREATE INDEX "idx_order_user_id" ON "orders" ("user_id" DESC);
CREATE INDEX "idx_order_package_id" ON "orders" ("package_id" DESC);
CREATE INDEX "idx_order_payment_code" ON "orders" ("payment_code" DESC);
CREATE INDEX "idx_transaction_order_id" ON "transactions" ("order_id" DESC);
CREATE INDEX "idx_general_logs_user_id" ON "general_logs" ("user_id" DESC);



-- INDEX UUID
CREATE INDEX "idx_user_uuid" ON "users" ("uuid");
CREATE INDEX "idx_group_uuid" ON "groups" ("uuid");
CREATE INDEX "idx_module_uuid" ON "modules" ("uuid");
CREATE INDEX "idx_sub_module_uuid" ON "sub_modules" ("uuid");
CREATE INDEX "idx_report_uuid" ON "reports" ("uuid");
CREATE INDEX "idx_user_sub_module_uuid" ON "user_sub_modules" ("uuid");
CREATE INDEX "idx_package_uuid" ON "packages" ("uuid");
CREATE INDEX "idx_user_membership_uuid" ON "user_memberships" ("uuid");
CREATE INDEX "idx_order_uuid" ON "orders" ("uuid");
CREATE INDEX "idx_transaction_uuid" ON "transactions" ("uuid");
CREATE INDEX "idx_general_logs_uuid" ON "general_logs" ("uuid");